name: build-and-smoke
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DH_USER }}
          password: ${{ secrets.DH_TOKEN }}
      - name: Buildx push
        uses: docker/build-push-action@v6
        with:
          push: true
          context: .
          tags: docker.io/${{ secrets.DH_USER }}/my_env:latest
          platforms: linux/amd64,linux/arm64
          provenance: true
      - name: Get digest
        id: digest
        run: |
          echo "DIGEST=$(docker buildx imagetools inspect docker.io/${{ secrets.DH_USER }}/my_env:latest | awk '/Digest:/ {print $2; exit}')" >> $GITHUB_OUTPUT
      - name: Smoke test (hud analyze)
        run: |
          python -m pip install -U pip
          python -m pip install "hud-python"
          hud analyze docker.io/${{ secrets.DH_USER }}/my_env@${{ steps.digest.outputs.DIGEST }} --live
